image:
  - Visual Studio 2015

platform:
  - x86
#  - x64

configuration:
  - Release

cache:
  - win_flex_bison-2.5.13.zip
  
install:
  # install python prereqs
  - python --version
  - python -m pip --version
  - python -m pip install Mako
  - python -m pip install pypiwin32
  - python -m pip install wheel
  - python -m pip install scons
  - scons --version

  # install flex/bison
  - if not exist win_flex_bison-2.5.13.zip appveyor DownloadFile "https://sourceforge.net/projects/winflexbison/files/win_flex_bison-2.5.13.zip"
  - 7z x -y -owinflexbison\ win_flex_bison-2.5.13.zip > nul
  - win_flex --version
  - win_bison --version
  
  - dir C:\Libraries\llvm-5.0.0

build_script:
  - cd C:\projects\angle-mesa-build
  - cd mesa
  - set Path=C:\projects\angle-mesa-build\winflexbison;%Path%
  - set LLVM=C:\Libraries\llvm-5.0.0
  - if "%PLATFORM%"=="x86" (scons machine=x86 platform=windows build=release texture_float=yes llvm=yes libgl-gdi)
#  - if "%PLATFORM%"=="x64" (scons machine=x86_64 platform=windows build=release texture_float=yes llvm=yes libgl-gdi)
